// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type LoginGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/login_controller.ts').default['show'], false>
}
type LoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/login_controller.ts').default['handle'], true>
}
type RegisterGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/register_controller.ts').default['show'], false>
}
type RegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['registerValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/register_controller.ts').default['handle'], true>
}
type ForgotPasswordGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/forgot_password_controller.ts').default['show'], false>
}
type ForgotPasswordPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['forgotPasswordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/forgot_password_controller.ts').default['handle'], true>
}
type ResetpasswordIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/reset_password_controller.ts').default['show'], false>
}
type ResetpasswordIdPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth_validator.ts')['resetPasswordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth/reset_password_controller.ts').default['handle'], true>
}
type AuthGoogleRedirectGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/social_controller.ts').default['redirect'], false>
}
type AuthGoogleCallbackGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/social_controller.ts').default['callback'], false>
}
type LogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth/logout_controller.ts').default['handle'], false>
}
type StaffTasksGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/task_controller.ts').default['index'], false>
}
type StaffPickupIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/pickup_controller.ts').default['index'], false>
}
type StaffPickupIdClaimPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/pickup_controller.ts').default['handle'], false>
}
type StaffPickupIdCompletePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/photo_validator.ts')['uploadPhotoValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/staff/pickup_controller.ts').default['complete'], true>
}
type StaffPickupIdCancelPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/pickup_controller.ts').default['cancel'], false>
}
type StaffInspectionIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/inspection_controller.ts').default['index'], false>
}
type StaffInspectionIdClaimPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/inspection_controller.ts').default['handle'], false>
}
type StaffInspectionIdCompletePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/photo_validator.ts')['inspectionValidatorWithPhoto']>>
  response: MakeTuyauResponse<import('../app/controllers/staff/inspection_controller.ts').default['complete'], true>
}
type StaffInspectionIdCancelPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/inspection_controller.ts').default['cancel'], false>
}
type StaffDeliveryIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/delivery_controller.ts').default['index'], false>
}
type StaffDeliveryIdClaimPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/delivery_controller.ts').default['handle'], false>
}
type StaffDeliveryIdCompletePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/photo_validator.ts')['uploadPhotoValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/staff/delivery_controller.ts').default['complete'], true>
}
type StaffDeliveryIdCancelPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/delivery_controller.ts').default['cancel'], false>
}
type StaffProfileGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/staff/profile_controller.ts').default['index'], false>
}
type StaffProfileChangepasswordPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/profile_validator.ts')['updatePasswordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/staff/profile_controller.ts').default['updatePassword'], true>
}
type OrderGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/order_controller.ts').default['create'], false>
}
type OrderPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/order_validator.ts')['orderValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/user/order_controller.ts').default['store'], true>
}
type OrdersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/order_controller.ts').default['index'], false>
}
type OrdersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/order_controller.ts').default['show'], false>
}
type OrdersStatusIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/order_controller.ts').default['status'], false>
}
type ProfileGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/profile_controller.ts').default['index'], false>
}
type ProfilePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/profile_validator.ts')['updateNameValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/user/profile_controller.ts').default['updateName'], true>
}
type ProfileChangepasswordPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/profile_validator.ts')['updatePasswordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/user/profile_controller.ts').default['updatePassword'], true>
}
type ProfileAddressGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/address_controller.ts').default['index'], false>
}
type ProfileAddressPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/address_validator.ts')['addressValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/user/address_controller.ts').default['store'], true>
}
type TransactionsDownpaymentIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/transactions/down_payment_controller.ts').default['index'], false>
}
type TransactionsDownpaymentIdPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/transactions/down_payment_controller.ts').default['handle'], false>
}
type TransactionsFullpaymentIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/transactions/full_payment_controller.ts').default['index'], false>
}
type TransactionsFullpaymentIdPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/transactions/down_payment_controller.ts').default['handle'], false>
}
type DownloadqrisIdIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/transactions/download_controller.ts').default['handle'], false>
}
type TransactionCallbackPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/user/transactions/notification_transaction_controller.ts').default['handle'], false>
}
type HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/health_checks_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'login': {
    '$url': {
    };
    '$get': LoginGetHead;
    '$head': LoginGetHead;
    '$post': LoginPost;
  };
  'register': {
    '$url': {
    };
    '$get': RegisterGetHead;
    '$head': RegisterGetHead;
    '$post': RegisterPost;
  };
  'forgot-password': {
    '$url': {
    };
    '$get': ForgotPasswordGetHead;
    '$head': ForgotPasswordGetHead;
    '$post': ForgotPasswordPost;
  };
  'reset-password': {
    ':token': {
      '$url': {
      };
      '$get': ResetpasswordIdGetHead;
      '$head': ResetpasswordIdGetHead;
      '$post': ResetpasswordIdPost;
    };
  };
  'auth': {
    'google': {
      'redirect': {
        '$url': {
        };
        '$get': AuthGoogleRedirectGetHead;
        '$head': AuthGoogleRedirectGetHead;
      };
      'callback': {
        '$url': {
        };
        '$get': AuthGoogleCallbackGetHead;
        '$head': AuthGoogleCallbackGetHead;
      };
    };
  };
  'logout': {
    '$url': {
    };
    '$post': LogoutPost;
  };
  'staff': {
    'tasks': {
      '$url': {
      };
      '$get': StaffTasksGetHead;
      '$head': StaffTasksGetHead;
    };
    'pickup': {
      ':id': {
        '$url': {
        };
        '$get': StaffPickupIdGetHead;
        '$head': StaffPickupIdGetHead;
        'claim': {
          '$url': {
          };
          '$post': StaffPickupIdClaimPost;
        };
        'complete': {
          '$url': {
          };
          '$post': StaffPickupIdCompletePost;
        };
        'cancel': {
          '$url': {
          };
          '$post': StaffPickupIdCancelPost;
        };
      };
    };
    'inspection': {
      ':id': {
        '$url': {
        };
        '$get': StaffInspectionIdGetHead;
        '$head': StaffInspectionIdGetHead;
        'claim': {
          '$url': {
          };
          '$post': StaffInspectionIdClaimPost;
        };
        'complete': {
          '$url': {
          };
          '$post': StaffInspectionIdCompletePost;
        };
        'cancel': {
          '$url': {
          };
          '$post': StaffInspectionIdCancelPost;
        };
      };
    };
    'delivery': {
      ':id': {
        '$url': {
        };
        '$get': StaffDeliveryIdGetHead;
        '$head': StaffDeliveryIdGetHead;
        'claim': {
          '$url': {
          };
          '$post': StaffDeliveryIdClaimPost;
        };
        'complete': {
          '$url': {
          };
          '$post': StaffDeliveryIdCompletePost;
        };
        'cancel': {
          '$url': {
          };
          '$post': StaffDeliveryIdCancelPost;
        };
      };
    };
    'profile': {
      '$url': {
      };
      '$get': StaffProfileGetHead;
      '$head': StaffProfileGetHead;
      'change-password': {
        '$url': {
        };
        '$post': StaffProfileChangepasswordPost;
      };
    };
  };
  'order': {
    '$url': {
    };
    '$get': OrderGetHead;
    '$head': OrderGetHead;
    '$post': OrderPost;
  };
  'orders': {
    '$url': {
    };
    '$get': OrdersGetHead;
    '$head': OrdersGetHead;
    ':id': {
      '$url': {
      };
      '$get': OrdersIdGetHead;
      '$head': OrdersIdGetHead;
    };
    'status': {
      ':id': {
        '$url': {
        };
        '$get': OrdersStatusIdGetHead;
        '$head': OrdersStatusIdGetHead;
      };
    };
  };
  'profile': {
    '$url': {
    };
    '$get': ProfileGetHead;
    '$head': ProfileGetHead;
    '$post': ProfilePost;
    'change-password': {
      '$url': {
      };
      '$post': ProfileChangepasswordPost;
    };
    'address': {
      '$url': {
      };
      '$get': ProfileAddressGetHead;
      '$head': ProfileAddressGetHead;
      '$put': ProfileAddressPut;
    };
  };
  'transactions': {
    'down-payment': {
      ':id': {
        '$url': {
        };
        '$get': TransactionsDownpaymentIdGetHead;
        '$head': TransactionsDownpaymentIdGetHead;
        '$post': TransactionsDownpaymentIdPost;
      };
    };
    'full-payment': {
      ':id': {
        '$url': {
        };
        '$get': TransactionsFullpaymentIdGetHead;
        '$head': TransactionsFullpaymentIdGetHead;
        '$post': TransactionsFullpaymentIdPost;
      };
    };
  };
  'download-qris': {
    ':qr': {
      ':id': {
        '$url': {
        };
        '$get': DownloadqrisIdIdGetHead;
        '$head': DownloadqrisIdIdGetHead;
      };
    };
  };
  'transaction': {
    'callback': {
      '$url': {
      };
      '$post': TransactionCallbackPost;
    };
  };
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/uploads/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'login.show',
    path: '/login',
    method: ["GET","HEAD"],
    types: {} as LoginGetHead,
  },
  {
    params: [],
    name: 'login.handle',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'register.show',
    path: '/register',
    method: ["GET","HEAD"],
    types: {} as RegisterGetHead,
  },
  {
    params: [],
    name: 'register.handle',
    path: '/register',
    method: ["POST"],
    types: {} as RegisterPost,
  },
  {
    params: [],
    name: 'forgot_password.show',
    path: '/forgot-password',
    method: ["GET","HEAD"],
    types: {} as ForgotPasswordGetHead,
  },
  {
    params: [],
    name: 'forgot_password.handle',
    path: '/forgot-password',
    method: ["POST"],
    types: {} as ForgotPasswordPost,
  },
  {
    params: ["token"],
    name: 'reset_password.show',
    path: '/reset-password/:token',
    method: ["GET","HEAD"],
    types: {} as ResetpasswordIdGetHead,
  },
  {
    params: ["token"],
    name: 'reset_password.handle',
    path: '/reset-password/:token',
    method: ["POST"],
    types: {} as ResetpasswordIdPost,
  },
  {
    params: [],
    name: 'social.show',
    path: '/auth/google/redirect',
    method: ["GET","HEAD"],
    types: {} as AuthGoogleRedirectGetHead,
  },
  {
    params: [],
    name: 'social.callback',
    path: '/auth/google/callback',
    method: ["GET","HEAD"],
    types: {} as AuthGoogleCallbackGetHead,
  },
  {
    params: [],
    name: 'logout.handle',
    path: '/logout',
    method: ["POST"],
    types: {} as LogoutPost,
  },
  {
    params: [],
    name: 'staff.tasks',
    path: '/staff/tasks',
    method: ["GET","HEAD"],
    types: {} as StaffTasksGetHead,
  },
  {
    params: ["id"],
    name: 'staff.pickup',
    path: '/staff/pickup/:id',
    method: ["GET","HEAD"],
    types: {} as StaffPickupIdGetHead,
  },
  {
    params: ["id"],
    name: 'staff.pickup.handle',
    path: '/staff/pickup/:id/claim',
    method: ["POST"],
    types: {} as StaffPickupIdClaimPost,
  },
  {
    params: ["id"],
    name: 'staff.pickup.complete',
    path: '/staff/pickup/:id/complete',
    method: ["POST"],
    types: {} as StaffPickupIdCompletePost,
  },
  {
    params: ["id"],
    name: 'staff.pickup.cancel',
    path: '/staff/pickup/:id/cancel',
    method: ["POST"],
    types: {} as StaffPickupIdCancelPost,
  },
  {
    params: ["id"],
    name: 'staff.inspection',
    path: '/staff/inspection/:id',
    method: ["GET","HEAD"],
    types: {} as StaffInspectionIdGetHead,
  },
  {
    params: ["id"],
    name: 'staff.inspection.handle',
    path: '/staff/inspection/:id/claim',
    method: ["POST"],
    types: {} as StaffInspectionIdClaimPost,
  },
  {
    params: ["id"],
    name: 'staff.inspection.complete',
    path: '/staff/inspection/:id/complete',
    method: ["POST"],
    types: {} as StaffInspectionIdCompletePost,
  },
  {
    params: ["id"],
    name: 'staff.inspection.cancel',
    path: '/staff/inspection/:id/cancel',
    method: ["POST"],
    types: {} as StaffInspectionIdCancelPost,
  },
  {
    params: ["id"],
    name: 'staff.delivery',
    path: '/staff/delivery/:id',
    method: ["GET","HEAD"],
    types: {} as StaffDeliveryIdGetHead,
  },
  {
    params: ["id"],
    name: 'staff.delivery.handle',
    path: '/staff/delivery/:id/claim',
    method: ["POST"],
    types: {} as StaffDeliveryIdClaimPost,
  },
  {
    params: ["id"],
    name: 'staff.delivery.complete',
    path: '/staff/delivery/:id/complete',
    method: ["POST"],
    types: {} as StaffDeliveryIdCompletePost,
  },
  {
    params: ["id"],
    name: 'staff.delivery.cancel',
    path: '/staff/delivery/:id/cancel',
    method: ["POST"],
    types: {} as StaffDeliveryIdCancelPost,
  },
  {
    params: [],
    name: 'staff.profile.show',
    path: '/staff/profile',
    method: ["GET","HEAD"],
    types: {} as StaffProfileGetHead,
  },
  {
    params: [],
    name: 'staff.profile.change_password.handle',
    path: '/staff/profile/change-password',
    method: ["POST"],
    types: {} as StaffProfileChangepasswordPost,
  },
  {
    params: [],
    name: 'orders.create',
    path: '/order',
    method: ["GET","HEAD"],
    types: {} as OrderGetHead,
  },
  {
    params: [],
    name: 'orders.store',
    path: '/order',
    method: ["POST"],
    types: {} as OrderPost,
  },
  {
    params: [],
    name: 'orders.index',
    path: '/orders',
    method: ["GET","HEAD"],
    types: {} as OrdersGetHead,
  },
  {
    params: ["id"],
    name: 'orders.show',
    path: '/orders/:id',
    method: ["GET","HEAD"],
    types: {} as OrdersIdGetHead,
  },
  {
    params: ["id"],
    name: 'orders.status',
    path: '/orders/status/:id',
    method: ["GET","HEAD"],
    types: {} as OrdersStatusIdGetHead,
  },
  {
    params: [],
    name: 'profile.show',
    path: '/profile',
    method: ["GET","HEAD"],
    types: {} as ProfileGetHead,
  },
  {
    params: [],
    name: 'profile.update',
    path: '/profile',
    method: ["POST"],
    types: {} as ProfilePost,
  },
  {
    params: [],
    name: 'profile.change_password.handle',
    path: '/profile/change-password',
    method: ["POST"],
    types: {} as ProfileChangepasswordPost,
  },
  {
    params: [],
    name: 'profile.address',
    path: '/profile/address',
    method: ["GET","HEAD"],
    types: {} as ProfileAddressGetHead,
  },
  {
    params: [],
    name: 'profile.address.handle',
    path: '/profile/address',
    method: ["PUT"],
    types: {} as ProfileAddressPut,
  },
  {
    params: ["id"],
    name: 'transactions.dp.show',
    path: '/transactions/down-payment/:id',
    method: ["GET","HEAD"],
    types: {} as TransactionsDownpaymentIdGetHead,
  },
  {
    params: ["id"],
    name: 'transactions.dp.handle',
    path: '/transactions/down-payment/:id',
    method: ["POST"],
    types: {} as TransactionsDownpaymentIdPost,
  },
  {
    params: ["id"],
    name: 'transactions.full.show',
    path: '/transactions/full-payment/:id',
    method: ["GET","HEAD"],
    types: {} as TransactionsFullpaymentIdGetHead,
  },
  {
    params: ["id"],
    name: 'transactions.full.handle',
    path: '/transactions/full-payment/:id',
    method: ["POST"],
    types: {} as TransactionsFullpaymentIdPost,
  },
  {
    params: ["qr","id"],
    name: 'download.qris',
    path: '/download-qris/:qr/:id',
    method: ["GET","HEAD"],
    types: {} as DownloadqrisIdIdGetHead,
  },
  {
    params: [],
    name: 'transactions.callback',
    path: '/transaction/callback',
    method: ["POST"],
    types: {} as TransactionCallbackPost,
  },
  {
    params: [],
    name: 'home',
    path: '/',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
declare module '@tuyau/inertia/types' {
  type InertiaApi = typeof api
  export interface Api extends InertiaApi {}
}
